/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * Represents caption details for a video.
 *
 * @param srclang The ISO 639-1 language code for the caption.
 * @param label A descriptive label for the caption.
 */


data class CaptionModel (

    /* The ISO 639-1 language code for the caption. */
    @SerializedName("srclang")
    val srclang: kotlin.String? = null,

    /* A descriptive label for the caption. */
    @SerializedName("label")
    val label: kotlin.String? = null

)

