/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * Schema for adding a caption. Includes language code, descriptive label, and a base64 encoded captions file.
 *
 * @param srclang The ISO 639-1 language code for the caption.
 * @param label A descriptive label for the caption.
 * @param captionsFile The base64 encoded captions file content.
 */


data class CaptionModelAdd (

    /* The ISO 639-1 language code for the caption. */
    @SerializedName("srclang")
    val srclang: kotlin.String? = null,

    /* A descriptive label for the caption. */
    @SerializedName("label")
    val label: kotlin.String? = null,

    /* The base64 encoded captions file content. */
    @SerializedName("captionsFile")
    val captionsFile: kotlin.String? = null

)

