/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * Represents a chapter within a video, including its title and start/end times.
 *
 * @param title The title of the chapter.
 * @param start The start time of the chapter in seconds.
 * @param end The end time of the chapter in seconds.
 */


data class ChapterModel (

    /* The title of the chapter. */
    @SerializedName("title")
    val title: kotlin.String,

    /* The start time of the chapter in seconds. */
    @SerializedName("start")
    val start: kotlin.Int? = null,

    /* The end time of the chapter in seconds. */
    @SerializedName("end")
    val end: kotlin.Int? = null

)

