/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * Represents a video collection in the library. Contains metadata such as the unique identifier, name, video count, total storage size, and preview information.
 *
 * @param videoLibraryId The ID of the video library that contains the collection.
 * @param guid The unique identifier of the collection.
 * @param name The name of the collection.
 * @param videoCount The number of videos in the collection.
 * @param totalSize The total storage size of the collection in bytes.
 * @param previewVideoIds Comma-separated list of video IDs used as preview icons.
 * @param previewImageUrls An array of URLs for preview images of the videos in the collection.
 */


data class CollectionModel (

    /* The ID of the video library that contains the collection. */
    @SerializedName("videoLibraryId")
    val videoLibraryId: kotlin.Long? = null,

    /* The unique identifier of the collection. */
    @SerializedName("guid")
    val guid: kotlin.String? = null,

    /* The name of the collection. */
    @SerializedName("name")
    val name: kotlin.String? = null,

    /* The number of videos in the collection. */
    @SerializedName("videoCount")
    val videoCount: kotlin.Long? = null,

    /* The total storage size of the collection in bytes. */
    @SerializedName("totalSize")
    val totalSize: kotlin.Long? = null,

    /* Comma-separated list of video IDs used as preview icons. */
    @SerializedName("previewVideoIds")
    val previewVideoIds: kotlin.String? = null,

    /* An array of URLs for preview images of the videos in the collection. */
    @SerializedName("previewImageUrls")
    val previewImageUrls: kotlin.collections.List<kotlin.String>? = null

)

