/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.UpdateCollectionModel

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param name The updated name of the collection.
 */


data class CollectionUpdateCollectionRequest (

    /* The updated name of the collection. */
    @SerializedName("name")
    val name: kotlin.String? = null

)

