/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * Schema for creating a new video entry. 'title' is required.
 *
 * @param title The title of the new video.
 * @param collectionId Optional collection ID where the video will be placed.
 * @param thumbnailTime Video time in milliseconds used to extract the main video thumbnail.
 */


data class CreateVideoModel (

    /* The title of the new video. */
    @SerializedName("title")
    val title: kotlin.String,

    /* Optional collection ID where the video will be placed. */
    @SerializedName("collectionId")
    val collectionId: kotlin.String? = null,

    /* Video time in milliseconds used to extract the main video thumbnail. */
    @SerializedName("thumbnailTime")
    val thumbnailTime: kotlin.Int? = null

)

