/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * Schema for fetching a video from a remote URL. The 'url' field is required.
 *
 * @param url The URL from which to fetch the video.
 * @param headers Optional headers to include with the fetch request.
 * @param title Optional title to assign to the fetched video.
 */


data class FetchVideoRequest (

    /* The URL from which to fetch the video. */
    @SerializedName("url")
    val url: kotlin.String,

    /* Optional headers to include with the fetch request. */
    @SerializedName("headers")
    val headers: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    /* Optional title to assign to the fetched video. */
    @SerializedName("title")
    val title: kotlin.String? = null

)

