/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * The issue code representing a specific transcoding problem. Codes: 0 = Undefined, 1 = StreamLengthsDifference, 2 = TranscodingWarnings, 3 = IncompatibleResolution, 4 = InvalidFramerate, 5 = VideoExceededMaxDuration, 6 = AudioExceededMaxDuration, 7 = OriginalCorrupted, 8 = TranscriptionFailed, 9 = JitIncompatible, 10 = JitFailed.
 *
 * Values: _0,_1,_2,_3,_4,_5,_6,_7,_8,_9,_10
 */

enum class IssueCodes(val value: kotlin.Int) {

    @SerializedName(value = "0")
    _0(0),

    @SerializedName(value = "1")
    _1(1),

    @SerializedName(value = "2")
    _2(2),

    @SerializedName(value = "3")
    _3(3),

    @SerializedName(value = "4")
    _4(4),

    @SerializedName(value = "5")
    _5(5),

    @SerializedName(value = "6")
    _6(6),

    @SerializedName(value = "7")
    _7(7),

    @SerializedName(value = "8")
    _8(8),

    @SerializedName(value = "9")
    _9(9),

    @SerializedName(value = "10")
    _10(10);

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value.toString()

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is IssueCodes) "$data" else null

        /**
         * Returns a valid [IssueCodes] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): IssueCodes? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

