/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * Represents a metadata tag for a video.
 *
 * @param `property` The property name of the meta tag.
 * @param `value` The value associated with the meta tag property.
 */


data class MetaTagModel (

    /* The property name of the meta tag. */
    @SerializedName("property")
    val `property`: kotlin.String? = null,

    /* The value associated with the meta tag property. */
    @SerializedName("value")
    val `value`: kotlin.String? = null

)

