/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * Represents a key moment in the video with a descriptive label and timestamp.
 *
 * @param label A descriptive label for the moment.
 * @param timestamp The timestamp of the moment in seconds.
 */


data class MomentModel (

    /* A descriptive label for the moment. */
    @SerializedName("label")
    val label: kotlin.String,

    /* The timestamp of the moment in seconds. */
    @SerializedName("timestamp")
    val timestamp: kotlin.Int? = null

)

