/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CollectionModel

import com.google.gson.annotations.SerializedName

/**
 * A paginated list of collections.
 *
 * @param totalItems The total number of collections available.
 * @param currentPage The current page number.
 * @param itemsPerPage The number of collections per page.
 * @param items The collections returned on the current page.
 */


data class PaginationListOfCollectionModel (

    /* The total number of collections available. */
    @SerializedName("totalItems")
    val totalItems: kotlin.Long? = null,

    /* The current page number. */
    @SerializedName("currentPage")
    val currentPage: kotlin.Long? = null,

    /* The number of collections per page. */
    @SerializedName("itemsPerPage")
    val itemsPerPage: kotlin.Int? = null,

    /* The collections returned on the current page. */
    @SerializedName("items")
    val items: kotlin.collections.List<CollectionModel>? = null

)

