/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * Reference to a specific video resolution including its file path.
 *
 * @param resolution The resolution (e.g., 720p, 1080p).
 * @param path The file path associated with this resolution.
 */


data class ResolutionReference (

    /* The resolution (e.g., 720p, 1080p). */
    @SerializedName("resolution")
    val resolution: kotlin.String? = null,

    /* The file path associated with this resolution. */
    @SerializedName("path")
    val path: kotlin.String? = null

)

