/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * Generic status response model indicating the success or failure of an operation.
 *
 * @param success Indicates whether the operation was successful.
 * @param message A descriptive message regarding the operation outcome.
 * @param statusCode The HTTP status code for the response.
 */


data class StatusModel (

    /* Indicates whether the operation was successful. */
    @SerializedName("success")
    val success: kotlin.Boolean? = null,

    /* A descriptive message regarding the operation outcome. */
    @SerializedName("message")
    val message: kotlin.String? = null,

    /* The HTTP status code for the response. */
    @SerializedName("statusCode")
    val statusCode: kotlin.Int? = null

)

