/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * Represents a storage object containing file details for a video.
 *
 * @param guid The unique identifier of the storage object.
 * @param storageZoneName The name of the storage zone where the file is kept.
 * @param path The file path of the storage object.
 * @param objectName The name of the object in storage.
 * @param length The length of the file in bytes.
 * @param lastChanged The date and time when the file was last modified.
 * @param serverId The identifier of the server storing the file.
 * @param isDirectory Indicates if the storage object is a directory.
 * @param userId The user ID associated with the storage object.
 * @param contentType The MIME type of the file.
 * @param dateCreated The date and time when the file was created.
 * @param storageZoneId The identifier of the storage zone.
 * @param checksum A checksum value for file integrity verification.
 * @param replicatedZones A list of storage zones where the file is replicated.
 */


data class StorageObjectModel (

    /* The unique identifier of the storage object. */
    @SerializedName("guid")
    val guid: kotlin.String? = null,

    /* The name of the storage zone where the file is kept. */
    @SerializedName("storageZoneName")
    val storageZoneName: kotlin.String? = null,

    /* The file path of the storage object. */
    @SerializedName("path")
    val path: kotlin.String? = null,

    /* The name of the object in storage. */
    @SerializedName("objectName")
    val objectName: kotlin.String? = null,

    /* The length of the file in bytes. */
    @SerializedName("length")
    val length: kotlin.Long? = null,

    /* The date and time when the file was last modified. */
    @SerializedName("lastChanged")
    val lastChanged: kotlin.String? = null,

    /* The identifier of the server storing the file. */
    @SerializedName("serverId")
    val serverId: kotlin.Int? = null,

    /* Indicates if the storage object is a directory. */
    @SerializedName("isDirectory")
    val isDirectory: kotlin.Boolean? = null,

    /* The user ID associated with the storage object. */
    @SerializedName("userId")
    val userId: kotlin.String? = null,

    /* The MIME type of the file. */
    @SerializedName("contentType")
    val contentType: kotlin.String? = null,

    /* The date and time when the file was created. */
    @SerializedName("dateCreated")
    val dateCreated: kotlin.String? = null,

    /* The identifier of the storage zone. */
    @SerializedName("storageZoneId")
    val storageZoneId: kotlin.Long? = null,

    /* A checksum value for file integrity verification. */
    @SerializedName("checksum")
    val checksum: kotlin.String? = null,

    /* A list of storage zones where the file is replicated. */
    @SerializedName("replicatedZones")
    val replicatedZones: kotlin.String? = null

)

