/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * Settings for video transcription that allow overriding default transcription options.
 *
 * @param targetLanguages List of target language codes (ISO 639-1) for transcription.
 * @param generateTitle Determines if the video title should be automatically generated.
 * @param generateDescription Determines if the video description should be automatically generated.
 * @param sourceLanguage The source language code (ISO 639-1) of the video. This takes precedence over the query parameter if provided.
 */


data class TranscribeSettings (

    /* List of target language codes (ISO 639-1) for transcription. */
    @SerializedName("targetLanguages")
    val targetLanguages: kotlin.collections.List<kotlin.String>? = null,

    /* Determines if the video title should be automatically generated. */
    @SerializedName("generateTitle")
    val generateTitle: kotlin.Boolean? = false,

    /* Determines if the video description should be automatically generated. */
    @SerializedName("generateDescription")
    val generateDescription: kotlin.Boolean? = false,

    /* The source language code (ISO 639-1) of the video. This takes precedence over the query parameter if provided. */
    @SerializedName("sourceLanguage")
    val sourceLanguage: kotlin.String? = null

)

