/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.IssueCodes
import org.openapitools.client.models.Severity

import com.google.gson.annotations.SerializedName

/**
 * Represents a message from the transcoding process indicating warnings or errors.
 *
 * @param timeStamp The timestamp when the message was generated.
 * @param level 
 * @param issueCode 
 * @param message A descriptive message detailing the transcoding issue.
 * @param `value` An optional value providing further context for the issue.
 */


data class TranscodingMessageModel (

    /* The timestamp when the message was generated. */
    @SerializedName("timeStamp")
    val timeStamp: kotlin.String? = null,

    @SerializedName("level")
    val level: Severity? = null,

    @SerializedName("issueCode")
    val issueCode: IssueCodes? = null,

    /* A descriptive message detailing the transcoding issue. */
    @SerializedName("message")
    val message: kotlin.String? = null,

    /* An optional value providing further context for the issue. */
    @SerializedName("value")
    val `value`: kotlin.String? = null

)

