/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * Schema for updating collection details.
 *
 * @param name The updated name of the collection.
 */


data class UpdateCollectionModel (

    /* The updated name of the collection. */
    @SerializedName("name")
    val name: kotlin.String? = null

)

