/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ChapterModel
import org.openapitools.client.models.MetaTagModel
import org.openapitools.client.models.MomentModel
import org.openapitools.client.models.UpdateVideoModel

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param title The updated title of the video.
 * @param collectionId The ID of the collection to which the video belongs.
 * @param chapters A list of chapters for the video.
 * @param moments A list of key moments in the video.
 * @param metaTags A list of meta tags to associate with the video.
 */


data class VideoUpdateVideoRequest (

    /* The updated title of the video. */
    @SerializedName("title")
    val title: kotlin.String? = null,

    /* The ID of the collection to which the video belongs. */
    @SerializedName("collectionId")
    val collectionId: kotlin.String? = null,

    /* A list of chapters for the video. */
    @SerializedName("chapters")
    val chapters: kotlin.collections.List<ChapterModel>? = null,

    /* A list of key moments in the video. */
    @SerializedName("moments")
    val moments: kotlin.collections.List<MomentModel>? = null,

    /* A list of meta tags to associate with the video. */
    @SerializedName("metaTags")
    val metaTags: kotlin.collections.List<MetaTagModel>? = null

)

