/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.VideoPlayDataModelVideo

import com.google.gson.annotations.SerializedName

/**
 * Contains all necessary playback information for a video, including various URLs and player configurations.
 *
 * @param video 
 * @param captionsPath The path where caption files are stored.
 * @param seekPath The URL to be used for seeking within the video.
 * @param thumbnailUrl The URL of the video's thumbnail.
 * @param fallbackUrl The fallback URL for the video.
 * @param videoPlaylistUrl The URL of the video playlist.
 * @param originalUrl The URL of the original video file.
 * @param previewUrl The URL of the video preview.
 * @param controls Player control settings.
 * @param enableDRM Indicates if DRM is enabled for the video.
 * @param drmVersion The version number of DRM used.
 * @param playerKeyColor The primary color used for the video player interface.
 * @param vastTagUrl The VAST tag URL for video ads.
 * @param captionsFontSize Font size for captions in the video player.
 * @param captionsFontColor Font color for captions in the video player.
 * @param captionsBackground Background color for captions.
 * @param uiLanguage The language used for the player UI.
 * @param allowEarlyPlay Indicates if early playback is allowed.
 * @param tokenAuthEnabled Indicates if token-based authentication is enabled for playback.
 * @param enableMP4Fallback Indicates if MP4 fallback files should be used.
 * @param showHeatmap Indicates if the heatmap should be displayed on the player.
 * @param fontFamily The font family used for captions.
 * @param playbackSpeeds Available playback speed options for the video.
 */


data class VideoPlayDataModel (

    @SerializedName("video")
    val video: VideoPlayDataModelVideo? = null,

    /* The path where caption files are stored. */
    @SerializedName("captionsPath")
    val captionsPath: kotlin.String? = null,

    /* The URL to be used for seeking within the video. */
    @SerializedName("seekPath")
    val seekPath: kotlin.String? = null,

    /* The URL of the video's thumbnail. */
    @SerializedName("thumbnailUrl")
    val thumbnailUrl: kotlin.String? = null,

    /* The fallback URL for the video. */
    @SerializedName("fallbackUrl")
    val fallbackUrl: kotlin.String? = null,

    /* The URL of the video playlist. */
    @SerializedName("videoPlaylistUrl")
    val videoPlaylistUrl: kotlin.String? = null,

    /* The URL of the original video file. */
    @SerializedName("originalUrl")
    val originalUrl: kotlin.String? = null,

    /* The URL of the video preview. */
    @SerializedName("previewUrl")
    val previewUrl: kotlin.String? = null,

    /* Player control settings. */
    @SerializedName("controls")
    val controls: kotlin.String? = null,

    /* Indicates if DRM is enabled for the video. */
    @SerializedName("enableDRM")
    val enableDRM: kotlin.Boolean? = null,

    /* The version number of DRM used. */
    @SerializedName("drmVersion")
    val drmVersion: kotlin.Int? = null,

    /* The primary color used for the video player interface. */
    @SerializedName("playerKeyColor")
    val playerKeyColor: kotlin.String? = null,

    /* The VAST tag URL for video ads. */
    @SerializedName("vastTagUrl")
    val vastTagUrl: kotlin.String? = null,

    /* Font size for captions in the video player. */
    @SerializedName("captionsFontSize")
    val captionsFontSize: kotlin.Int? = null,

    /* Font color for captions in the video player. */
    @SerializedName("captionsFontColor")
    val captionsFontColor: kotlin.String? = null,

    /* Background color for captions. */
    @SerializedName("captionsBackground")
    val captionsBackground: kotlin.String? = null,

    /* The language used for the player UI. */
    @SerializedName("uiLanguage")
    val uiLanguage: kotlin.String? = null,

    /* Indicates if early playback is allowed. */
    @SerializedName("allowEarlyPlay")
    val allowEarlyPlay: kotlin.Boolean? = null,

    /* Indicates if token-based authentication is enabled for playback. */
    @SerializedName("tokenAuthEnabled")
    val tokenAuthEnabled: kotlin.Boolean? = null,

    /* Indicates if MP4 fallback files should be used. */
    @SerializedName("enableMP4Fallback")
    val enableMP4Fallback: kotlin.Boolean? = null,

    /* Indicates if the heatmap should be displayed on the player. */
    @SerializedName("showHeatmap")
    val showHeatmap: kotlin.Boolean? = null,

    /* The font family used for captions. */
    @SerializedName("fontFamily")
    val fontFamily: kotlin.String? = null,

    /* Available playback speed options for the video. */
    @SerializedName("playbackSpeeds")
    val playbackSpeeds: kotlin.String? = null

)

