/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * Represents the heatmap data for a video. Each key represents a time segment and its corresponding watch percentage.
 *
 * @param heatmap The heatmap where keys are time segments and values are watch percentages.
 */


data class VideoHeatmapModel (

    /* The heatmap where keys are time segments and values are watch percentages. */
    @SerializedName("heatmap")
    val heatmap: kotlin.collections.Map<kotlin.String, kotlin.Int>? = null

)

