/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * Represents various statistics for a video including view counts, watch time, and engagement score.
 *
 * @param viewsChart A chart representing view counts over time.
 * @param watchTimeChart A chart representing total watch time over time.
 * @param countryViewCounts View counts grouped by country.
 * @param countryWatchTime Total watch time grouped by country.
 * @param engagementScore A score representing viewer engagement.
 */


data class VideoStatisticsModel (

    /* A chart representing view counts over time. */
    @SerializedName("viewsChart")
    val viewsChart: kotlin.collections.Map<kotlin.String, kotlin.Long>? = null,

    /* A chart representing total watch time over time. */
    @SerializedName("watchTimeChart")
    val watchTimeChart: kotlin.collections.Map<kotlin.String, kotlin.Long>? = null,

    /* View counts grouped by country. */
    @SerializedName("countryViewCounts")
    val countryViewCounts: kotlin.collections.Map<kotlin.String, kotlin.Long>? = null,

    /* Total watch time grouped by country. */
    @SerializedName("countryWatchTime")
    val countryWatchTime: kotlin.collections.Map<kotlin.String, kotlin.Long>? = null,

    /* A score representing viewer engagement. */
    @SerializedName("engagementScore")
    val engagementScore: kotlin.Int? = null

)

