/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * Represents OEmbed data for a video, including embed HTML and metadata such as title and provider information.
 *
 * @param version The version of the OEmbed specification being used.
 * @param title The title of the video.
 * @param type The type of the embedded object (e.g., video).
 * @param thumbnailUrl The URL of the video thumbnail.
 * @param width The width of the embedded video.
 * @param height The height of the embedded video.
 * @param html The HTML snippet for embedding the video.
 * @param providerName The name of the provider (e.g., bunny.net).
 * @param providerUrl The URL of the provider's website.
 */


data class VideoOEmbedModel (

    /* The version of the OEmbed specification being used. */
    @SerializedName("version")
    val version: kotlin.String? = null,

    /* The title of the video. */
    @SerializedName("title")
    val title: kotlin.String? = null,

    /* The type of the embedded object (e.g., video). */
    @SerializedName("type")
    val type: kotlin.String? = null,

    /* The URL of the video thumbnail. */
    @SerializedName("thumbnailUrl")
    val thumbnailUrl: kotlin.String? = null,

    /* The width of the embedded video. */
    @SerializedName("width")
    val width: kotlin.Int? = null,

    /* The height of the embedded video. */
    @SerializedName("height")
    val height: kotlin.Int? = null,

    /* The HTML snippet for embedding the video. */
    @SerializedName("html")
    val html: kotlin.String? = null,

    /* The name of the provider (e.g., bunny.net). */
    @SerializedName("providerName")
    val providerName: kotlin.String? = null,

    /* The URL of the provider's website. */
    @SerializedName("providerUrl")
    val providerUrl: kotlin.String? = null

)

