/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ResolutionReference
import org.openapitools.client.models.StorageObjectModel

import com.google.gson.annotations.SerializedName

/**
 * Represents detailed resolution information for a video, including available, configured, and storage resolutions.
 *
 * @param videoId The unique identifier of the video.
 * @param videoLibraryId The ID of the video library.
 * @param availableResolutions A list of available resolutions for the video.
 * @param configuredResolutions A list of resolutions configured for encoding.
 * @param playlistResolutions A list of resolutions used in playlists.
 * @param storageResolutions A list of resolutions stored on the server.
 * @param mp4Resolutions A list of MP4 fallback resolutions.
 * @param storageObjects A list of storage objects related to the video resolutions.
 * @param oldResolutions A list of previous resolution objects that may be removed.
 * @param hasBothOldAndNewResolutionFormat Indicates if both old and new resolution formats are present.
 * @param hasOriginal Indicates if the original video file is available.
 */


data class VideoResolutionsInfoModel (

    /* The unique identifier of the video. */
    @SerializedName("videoId")
    val videoId: kotlin.String? = null,

    /* The ID of the video library. */
    @SerializedName("videoLibraryId")
    val videoLibraryId: kotlin.Long? = null,

    /* A list of available resolutions for the video. */
    @SerializedName("availableResolutions")
    val availableResolutions: kotlin.collections.List<kotlin.String>? = null,

    /* A list of resolutions configured for encoding. */
    @SerializedName("configuredResolutions")
    val configuredResolutions: kotlin.collections.List<kotlin.String>? = null,

    /* A list of resolutions used in playlists. */
    @SerializedName("playlistResolutions")
    val playlistResolutions: kotlin.collections.List<ResolutionReference>? = null,

    /* A list of resolutions stored on the server. */
    @SerializedName("storageResolutions")
    val storageResolutions: kotlin.collections.List<ResolutionReference>? = null,

    /* A list of MP4 fallback resolutions. */
    @SerializedName("mp4Resolutions")
    val mp4Resolutions: kotlin.collections.List<ResolutionReference>? = null,

    /* A list of storage objects related to the video resolutions. */
    @SerializedName("storageObjects")
    val storageObjects: kotlin.collections.List<StorageObjectModel>? = null,

    /* A list of previous resolution objects that may be removed. */
    @SerializedName("oldResolutions")
    val oldResolutions: kotlin.collections.List<StorageObjectModel>? = null,

    /* Indicates if both old and new resolution formats are present. */
    @SerializedName("hasBothOldAndNewResolutionFormat")
    val hasBothOldAndNewResolutionFormat: kotlin.Boolean? = null,

    /* Indicates if the original video file is available. */
    @SerializedName("hasOriginal")
    val hasOriginal: kotlin.Boolean? = null

)

